### ISSUE TITLE
Bug: Huge CPU/Battery consumption

### ISSUE THREAD

**Issue by datrinh** [angular/vscode-ng-language-service#69]
Specs:
MacBook Pro (Retina, 13", Late  2013) 
OS: OS X El Capitan 10.11.6
VS Code: Version 1.11.1 (1.11.1)

So today I noticed my fan running even tho I was hardly running any apps in the background. Also my battery was draining way faster than usual. A look into the task manager found the culprit:

![aktivitatsanzeige meine prozesse 2017-04-06 22-09-48](https://cloud.githubusercontent.com/assets/3518618/24773764/b56ce4f2-1b16-11e7-8338-1858c3ee066a.png)

After deactivating and reactivating every single extension, it was this one that caused the problem. Is anyone else experiencing this?

**Comment by chuckjaz** [comment]
I appreciate you narrow this down. I have seen reports of this but have not been able to track down the cause. Do you have a project I can clone or a .zip file I can download that can reproduce this?

**Comment by datrinh** [comment]
In my case, there are no special steps needed to repro this problem. Opening VS Code without a folder open and then creating a new simple html file already causes this.

So to repro with my setup:

1. Open VS Code without folder or close all folders
2. Create a new html file
3. Fill it with some boilerplate [1]
4. Save the file

[1]
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>title</title>
  </head>
  <body>
  
  </body>
</html>
```

**Comment by janhjordie** [comment]
I also have the same issue. My VS Code uses 53% of CPU on my Win 10. 
If I disable the plugin and restart VS Code, the CPU drops to 1-2% .

**Comment by okonon** [comment]
@chuckjaz please see #73 for sample project to reproduce this

**Comment by fxck** [comment]
I'm seeing this as well, it's not always immediate and it also seems to be happening _even_ when I'm running an incompatible version of ts (2.2).

**Comment by d3viant0ne** [comment]
![screen shot 2017-04-08 at 11 29 01 am](https://cloud.githubusercontent.com/assets/8420490/24830586/cb12ce3c-1c4e-11e7-8f19-c02de1cd54fd.png)

It will maintain that CPU usage until I manually kill the process.

Grabbed a dump of the process on the off chance that's going to be of use.

[vscode_processdump.txt](https://github.com/Microsoft/vscode/files/907627/vscode_processdump.txt)

For reference, you don't need an Angular project to reproduce this. It buried my CPU while I was working on Webpack loaders.

**Comment by askerb** [comment]
I'm also experiencing this running macOS Sierra 10.12.4 and Visual Studio Code 1.11.1.
Code Helper running att full CPU until I manually kill the process. Turning off the Angular language service as suggested solved the issue.

**Comment by chuckjaz** [comment]
I have reproduced this with @datrinh repro steps. I am working on this now. I plan another release when I have this fixed and #32 fixed.

**Comment by chuckjaz** [comment]
Tracking in https://github.com/angular/angular/issues/15874

**Comment by chuckjaz** [comment]
This should be fixed in `0.1.3`. Reopen if it continues to reproduce.

**Comment by littleStudent** [comment]
0.1.3 same issue for me.

**Comment by chuckjaz** [comment]
@littleStudent Can you describe the issue you are having because the issue above was fixed. In other words, I believe you are having a different issue than the above that happens to look similar.

**Comment by d3viant0ne** [comment]
@chuckjaz - I've tried to reproduce this with both my steps and those of @datrinh in `v0.1.3` using `@code & @code-insiders`. The CPU issue and the zombie thread issue hasn't cropped up again.

**Comment by littleStudent** [comment]
@chuckjaz I will try to pin point this and make a separate issue if its a different bug.

**Comment by fxck** [comment]
![image](https://cloud.githubusercontent.com/assets/1303561/25012614/51155024-2071-11e7-9f05-4c11b5c7be29.png)

still happening

**Comment by chuckjaz** [comment]
@fxck Can I get more information about how to reproduce what you are seeing. Do you have a project I can clone?

**Comment by fxck** [comment]
Unfortunately not a project I can share. I can't really figure out how to reproduce it. I'm not sure if it's related, but I'm running TS2.2.2, which is not compatible, so the plugin shouldn't really be running at all?

**Comment by chuckjaz** [comment]
@fxck Can you try reproducing with a smaller, sharable TS2.2 project?

**Comment by d3viant0ne** [comment]
I'll try spinning up a cli app and see if I can get it to crop up.

The issue where the plugin was eating up a ton of CPU while working in a plain JavaScript project hasn't happened again since the upgrade to `v0.1.3` and enabling the plugin again. Whatever portion of this issue still exists, it looks to be specific to some sort of TypeScript project.
